/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    google()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")


    implementation(libs.guava)
    implementation("stax:stax-api:1.0.1")
    implementation("com.mysql:mysql-connector-j:9.1.0")
    implementation("org.json:json:20250107")

    implementation("com.google.firebase:firebase-admin:9.4.0")

    implementation("com.google.protobuf:protobuf-java:4.31.1")
    implementation("io.jsonwebtoken:jjwt-api:0.12.6")
    implementation("com.zaxxer:HikariCP:7.0.2")
    runtimeOnly("io.jsonwebtoken:jjwt-impl:0.12.6")
    implementation("org.mindrot:jbcrypt:0.4")
    implementation("com.googlecode.json-simple:json-simple:1.1.1")

    implementation("com.cloudinary:cloudinary-http5:2.3.2")
    //implementation("io.github.f4b6a3:ulid-creator:5.2.3")
    implementation("com.github.f4b6a3:ulid-creator:5.2.4")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = "streammessenger.App"
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}
tasks.jar {
    manifest {
        attributes["Main-Class"] = "streammessenger.App"
    }
}
